export const jobFormOptions = {
  category: ["Teaching", "Non-teaching"],
  specialization: [
    "Kindergarten",
    "Elementary",
    "Middle School",
    "High School",
    "University",
    "Corporate English",
    "Private Tutoring",
    "Frontend",
    "Backend",
    "Full-stack",
    "Design",
    "Marketing",
    "Sales",
    "HR",
    "Finance",
    "Customer Support",
  ],
  contractType: ["Full-time", "Part-time"],
  province: [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Sejong",
    "Gyeonggi-do",
    "Gangwon-do",
    "Chungcheongbuk-do",
    "Chungcheongnam-do",
    "Jeollabuk-do",
    "Jeollanam-do",
    "Gyeongsangbuk-do",
    "Gyeongsangnam-do",
    "Jeju-do",
  ],
  city: [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Sejong",
    "Suwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Ansan",
    "Anyang",
    "Namyangju",
    "Hwaseong",
    "Uijeongbu",
    "Pyeongtaek",
    "Siheung",
    "Paju",
    "Gimpo",
    "Gwangmyeong",
    "Gunpo",
    "Osan",
    "Icheon",
    "Chuncheon",
    "Wonju",
    "Gangneung",
    "Sokcho",
    "Donghae",
    "Samcheok",
    "Cheonan",
    "Cheongju",
    "Chungju",
    "Jecheon",
    "Asan",
    "Seosan",
    "Dangjin",
    "Gongju",
    "Boryeong",
    "Nonsan",
    "Jeonju",
    "Iksan",
    "Gunsan",
    "Jeongeup",
    "Namwon",
    "Gimje",
    "Yeosu",
    "Suncheon",
    "Mokpo",
    "Naju",
    "Gwangyang",
    "Changwon",
    "Pohang",
    "Gyeongju",
    "Gumi",
    "Andong",
    "Gyeongsan",
    "Yeongju",
    "Yeongcheon",
    "Gimhae",
    "Jinju",
    "Yangsan",
    "Geoje",
    "Tongyeong",
    "Miryang",
    "Sacheon",
    "Jeju",
    "Seogwipo",
    "Gangnam-gu",
    "Gangdong-gu",
    "Gangbuk-gu",
    "Gangseo-gu",
    "Gwanak-gu",
    "Gwangjin-gu",
    "Guro-gu",
    "Geumcheon-gu",
    "Nowon-gu",
    "Dobong-gu",
    "Dongdaemun-gu",
    "Dongjak-gu",
    "Mapo-gu",
    "Seodaemun-gu",
    "Seocho-gu",
    "Seongdong-gu",
    "Seongbuk-gu",
    "Songpa-gu",
    "Yangcheon-gu",
    "Yeongdeungpo-gu",
    "Yongsan-gu",
    "Eunpyeong-gu",
    "Jongno-gu",
    "Jung-gu",
    "Jungnang-gu",
    "Dong-gu",
    "Seo-gu",
    "Yeongdo-gu",
    "Busanjin-gu",
    "Dongnae-gu",
    "Nam-gu",
    "Buk-gu",
    "Haeundae-gu",
    "Saha-gu",
    "Geumjeong-gu",
    "Yeonje-gu",
    "Suyeong-gu",
    "Sasang-gu",
    "Gijang-gun",
    "Suseong-gu",
    "Dalseo-gu",
    "Dalseong-gun",
    "Gunwi-gun",
    "Michuhol-gu",
    "Yeonsu-gu",
    "Namdong-gu",
    "Bupyeong-gu",
    "Gyeyang-gu",
    "Ganghwa-gun",
    "Ongjin-gun",
    "Gwangsan-gu",
    "Yuseong-gu",
    "Daedeok-gu",
    "Ulju-gun",
    "Hansol-dong",
    "Saerom-dong",
    "Naseong-dong",
    "Dodam-dong",
    "Eojin-dong",
    "Areum-dong",
    "Jongchon-dong",
    "Goun-dong",
    "Boram-dong",
    "Daepyeong-dong",
    "Sodam-dong",
    "Dajeong-dong",
    "Haemil-dong",
    "Bangok-dong",
    "Jochiwon-eup",
    "Yeongi-myeon",
    "Yeondong-myeon",
    "Bugang-myeon",
    "Geumnam-myeon",
    "Janggun-myeon",
    "Yeonseo-myeon",
    "Jeonui-myeon",
    "Jeondong-myeon",
    "Sojeong-myeon",
  ],

  koreanProficiency: [
    { value: 0, label: "Not Required" },
    { value: 1, label: "Beginner" },
    { value: 2, label: "Intermediate" },
  ],
  englishProficiency: [
    { value: 0, label: "Not Required" },
    { value: 1, label: "Beginner" },
    { value: 2, label: "Intermediate" },
  ],
  visaSponsorship: ["Not Provided", "Provided"],
  startDate: [
    "ASAP",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  contactMethod: ["link", "relay"],
} as const;

export const specializationsByCategory = {
  Teaching: [
    "Kindergarten",
    "Elementary",
    "Middle School",
    "High School",
    "University",
    "Corporate English",
    "Private Tutoring",
  ],
  "Non-teaching": [
    "Frontend",
    "Backend",
    "Full-stack",
    "Design",
    "Marketing",
    "Sales",
    "HR",
    "Finance",
    "Customer Support",
  ],
};

export const citiesByProvince = {
  Seoul: [
    "Gangnam-gu",
    "Gangdong-gu",
    "Gangbuk-gu",
    "Gangseo-gu",
    "Gwanak-gu",
    "Gwangjin-gu",
    "Guro-gu",
    "Geumcheon-gu",
    "Nowon-gu",
    "Dobong-gu",
    "Dongdaemun-gu",
    "Dongjak-gu",
    "Mapo-gu",
    "Seodaemun-gu",
    "Seocho-gu",
    "Seongdong-gu",
    "Seongbuk-gu",
    "Songpa-gu",
    "Yangcheon-gu",
    "Yeongdeungpo-gu",
    "Yongsan-gu",
    "Eunpyeong-gu",
    "Jongno-gu",
    "Jung-gu",
    "Jungnang-gu",
  ],
  Busan: [
    "Jung-gu",
    "Seo-gu",
    "Dong-gu",
    "Yeongdo-gu",
    "Busanjin-gu",
    "Dongnae-gu",
    "Nam-gu",
    "Buk-gu",
    "Haeundae-gu",
    "Saha-gu",
    "Geumjeong-gu",
    "Gangseo-gu",
    "Yeonje-gu",
    "Suyeong-gu",
    "Sasang-gu",
    "Gijang-gun",
  ],
  Daegu: [
    "Jung-gu",
    "Dong-gu",
    "Seo-gu",
    "Nam-gu",
    "Buk-gu",
    "Suseong-gu",
    "Dalseo-gu",
    "Dalseong-gun",
    "Gunwi-gun",
  ],
  Incheon: [
    "Jung-gu",
    "Dong-gu",
    "Michuhol-gu",
    "Yeonsu-gu",
    "Namdong-gu",
    "Bupyeong-gu",
    "Gyeyang-gu",
    "Seo-gu",
    "Ganghwa-gun",
    "Ongjin-gun",
  ],
  Gwangju: ["Dong-gu", "Seo-gu", "Nam-gu", "Buk-gu", "Gwangsan-gu"],
  Daejeon: ["Dong-gu", "Jung-gu", "Seo-gu", "Yuseong-gu", "Daedeok-gu"],
  Ulsan: ["Jung-gu", "Nam-gu", "Dong-gu", "Buk-gu", "Ulju-gun"],
  Sejong: [
    "Hansol-dong",
    "Saerom-dong",
    "Naseong-dong",
    "Dodam-dong",
    "Eojin-dong",
    "Areum-dong",
    "Jongchon-dong",
    "Goun-dong",
    "Boram-dong",
    "Daepyeong-dong",
    "Sodam-dong",
    "Dajeong-dong",
    "Haemil-dong",
    "Bangok-dong",
    "Jochiwon-eup",
  ],
  "Gyeonggi-do": [
    "Suwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Ansan",
    "Anyang",
    "Namyangju",
    "Hwaseong",
    "Uijeongbu",
    "Pyeongtaek",
    "Siheung",
    "Paju",
    "Gimpo",
    "Gwangmyeong",
    "Gunpo",
    "Osan",
    "Icheon",
  ],
  "Gangwon-do": [
    "Chuncheon",
    "Wonju",
    "Gangneung",
    "Sokcho",
    "Donghae",
    "Samcheok",
  ],
  "Chungcheongbuk-do": ["Cheongju", "Chungju", "Jecheon"],
  "Chungcheongnam-do": [
    "Cheonan",
    "Asan",
    "Seosan",
    "Dangjin",
    "Gongju",
    "Boryeong",
    "Nonsan",
  ],
  "Jeollabuk-do": ["Jeonju", "Iksan", "Gunsan", "Jeongeup", "Namwon", "Gimje"],
  "Jeollanam-do": ["Yeosu", "Suncheon", "Mokpo", "Naju", "Gwangyang"],
  "Gyeongsangbuk-do": [
    "Pohang",
    "Gyeongju",
    "Gumi",
    "Andong",
    "Gyeongsan",
    "Yeongju",
    "Yeongcheon",
  ],
  "Gyeongsangnam-do": [
    "Changwon",
    "Gimhae",
    "Jinju",
    "Yangsan",
    "Geoje",
    "Tongyeong",
    "Miryang",
    "Sacheon",
  ],
  "Jeju-do": ["Jeju", "Seogwipo"],
};
