export const specializationsByCategory = {
  Teaching: [
    "Kindergarten",
    "Elementary",
    "Kindergarten + Elementary",
    "Middle School",
    "High School",
    "University",
    "Adults",
    "English Cafe",
    "Business English",
    "Private Tutoring",
  ],
  "Non-teaching": [
    "Frontend",
    "Backend",
    "Full-stack",
    "Design",
    "Marketing",
    "Sales",
    "HR",
    "Finance",
    "Customer Support",
  ],
};

export const citiesByProvince = {
  Seoul: [
    "Gangnam-gu",
    "Gangdong-gu",
    "Gangbuk-gu",
    "Gangseo-gu",
    "Gwanak-gu",
    "Gwangjin-gu",
    "Guro-gu",
    "Geumcheon-gu",
    "Nowon-gu",
    "Dobong-gu",
    "Dongdaemun-gu",
    "Dongjak-gu",
    "Mapo-gu",
    "Seodaemun-gu",
    "Seocho-gu",
    "Seongdong-gu",
    "Seongbuk-gu",
    "Songpa-gu",
    "Yangcheon-gu",
    "Yeongdeungpo-gu",
    "Yongsan-gu",
    "Eunpyeong-gu",
    "Jongno-gu",
    "Jung-gu",
    "Jungnang-gu",
  ],
  Busan: [
    "Jung-gu",
    "Seo-gu",
    "Dong-gu",
    "Yeongdo-gu",
    "Busanjin-gu",
    "Dongnae-gu",
    "Nam-gu",
    "Buk-gu",
    "Haeundae-gu",
    "Saha-gu",
    "Geumjeong-gu",
    "Gangseo-gu",
    "Yeonje-gu",
    "Suyeong-gu",
    "Sasang-gu",
    "Gijang-gun",
  ],
  Daegu: [
    "Jung-gu",
    "Dong-gu",
    "Seo-gu",
    "Nam-gu",
    "Buk-gu",
    "Suseong-gu",
    "Dalseo-gu",
    "Dalseong-gun",
    "Gunwi-gun",
  ],
  Incheon: [
    "Jung-gu",
    "Dong-gu",
    "Michuhol-gu",
    "Yeonsu-gu",
    "Namdong-gu",
    "Bupyeong-gu",
    "Gyeyang-gu",
    "Seo-gu",
    "Ganghwa-gun",
    "Ongjin-gun",
  ],
  Gwangju: ["Dong-gu", "Seo-gu", "Nam-gu", "Buk-gu", "Gwangsan-gu"],
  Daejeon: ["Dong-gu", "Jung-gu", "Seo-gu", "Yuseong-gu", "Daedeok-gu"],
  Ulsan: ["Jung-gu", "Nam-gu", "Dong-gu", "Buk-gu", "Ulju-gun"],
  Sejong: [
    "Hansol-dong",
    "Saerom-dong",
    "Naseong-dong",
    "Dodam-dong",
    "Eojin-dong",
    "Areum-dong",
    "Jongchon-dong",
    "Goun-dong",
    "Boram-dong",
    "Daepyeong-dong",
    "Sodam-dong",
    "Dajeong-dong",
    "Haemil-dong",
    "Bangok-dong",
    "Jochiwon-eup",
  ],
  "Gyeonggi-do": [
    "Suwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Ansan",
    "Anyang",
    "Namyangju",
    "Hwaseong",
    "Uijeongbu",
    "Pyeongtaek",
    "Siheung",
    "Paju",
    "Gimpo",
    "Gwangmyeong",
    "Gunpo",
    "Osan",
    "Icheon",
  ],
  "Gangwon-do": [
    "Chuncheon",
    "Wonju",
    "Gangneung",
    "Sokcho",
    "Donghae",
    "Samcheok",
  ],
  "Chungcheongbuk-do": ["Cheongju", "Chungju", "Jecheon"],
  "Chungcheongnam-do": [
    "Cheonan",
    "Asan",
    "Seosan",
    "Dangjin",
    "Gongju",
    "Boryeong",
    "Nonsan",
  ],
  "Jeollabuk-do": ["Jeonju", "Iksan", "Gunsan", "Jeongeup", "Namwon", "Gimje"],
  "Jeollanam-do": ["Yeosu", "Suncheon", "Mokpo", "Naju", "Gwangyang"],
  "Gyeongsangbuk-do": [
    "Pohang",
    "Gyeongju",
    "Gumi",
    "Andong",
    "Gyeongsan",
    "Yeongju",
    "Yeongcheon",
  ],
  "Gyeongsangnam-do": [
    "Changwon",
    "Gimhae",
    "Jinju",
    "Yangsan",
    "Geoje",
    "Tongyeong",
    "Miryang",
    "Sacheon",
  ],
  "Jeju-do": ["Jeju", "Seogwipo"],
};

export const jobFormOptions = {
  category: Object.keys(specializationsByCategory),
  specialization: Object.values(specializationsByCategory).flat(),
  contractType: ["Full-time", "Part-time", "Contract", "Temporary"],
  province: Object.keys(citiesByProvince),
  city: Object.values(citiesByProvince).flat(),

  koreanProficiency: [
    "Not Required",
    "Beginner Korean",
    "Intermediate Korean",
    "Conversational Korean",
    "Fluent Korean",
    "Native Korean",
  ],
  englishProficiency: [
    "Not Required",
    "Beginner English",
    "Intermediate English",
    "Conversational English",
    "Fluent English",
    "Native English",
  ],
  visaSponsorship: ["Provided", "Not Provided", "Possible"],
  startDate: [
    "ASAP",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  contactMethod: ["link", "relay"],
} as const;
