export const jobFormOptions = {
  category: ["Teaching", "Non-teaching"],
  specialization: [
    "Kindergarten",
    "Elementary",
    "Middle School",
    "High School",
    "University",
    "Corporate English",
    "Private Tutoring",
    "Frontend",
    "Backend",
    "Full-stack",
    "Design",
    "Marketing",
    "Sales",
    "HR",
    "Finance",
    "Customer Support",
  ],
  contractType: ["Full-time", "Part-time"],
  province: [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Sejong",
    "Gyeonggi-do",
    "Gangwon-do",
    "Chungcheongbuk-do",
    "Chungcheongnam-do",
    "Jeollabuk-do",
    "Jeollanam-do",
    "Gyeongsangbuk-do",
    "Gyeongsangnam-do",
    "Jeju-do",
  ],
  city: [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Sejong",
    "Suwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Ansan",
    "Anyang",
    "Namyangju",
    "Hwaseong",
    "Uijeongbu",
    "Cheonan",
    "Jeonju",
    "Cheongju",
    "Changwon",
    "Pohang",
    "Gimhae",
    "Jeju",
  ],

  koreanProficiency: [
    { value: 0, label: "Not Required" },
    { value: 1, label: "Beginner" },
    { value: 2, label: "Intermediate" },
  ],
  englishProficiency: [
    { value: 0, label: "Not Required" },
    { value: 1, label: "Beginner" },
    { value: 2, label: "Intermediate" },
  ],
  visaSponsorship: ["Not Provided", "Provided"],
  startDate: [
    "ASAP",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  contactMethod: ["link", "relay"],
} as const;

export const specializationsByCategory = {
  Teaching: [
    "Kindergarten",
    "Elementary",
    "Middle School",
    "High School",
    "University",
    "Corporate English",
    "Private Tutoring",
  ],
  "Non-teaching": [
    "Frontend",
    "Backend",
    "Full-stack",
    "Design",
    "Marketing",
    "Sales",
    "HR",
    "Finance",
    "Customer Support",
  ],
};

export const citiesByProvince = {
  Seoul: ["Seoul"],
  Busan: ["Busan"],
  Daegu: ["Daegu"],
  Incheon: ["Incheon"],
  Gwangju: ["Gwangju"],
  Daejeon: ["Daejeon"],
  Ulsan: ["Ulsan"],
  Sejong: ["Sejong"],
  "Gyeonggi-do": ["Suwon", "Seongnam", "Goyang", "Yongin", "Bucheon", "Ansan", "Anyang", "Namyangju", "Hwaseong", "Uijeongbu"],
  "Gangwon-do": ["Chuncheon", "Wonju", "Gangneung"],
  "Chungcheongbuk-do": ["Cheongju", "Chungju"],
  "Chungcheongnam-do": ["Cheonan", "Asan", "Cheonan"],
  "Jeollabuk-do": ["Jeonju", "Iksan", "Gunsan"],
  "Jeollanam-do": ["Yeosu", "Suncheon", "Mokpo"],
  "Gyeongsangbuk-do": ["Pohang", "Gyeongju", "Gumi"],
  "Gyeongsangnam-do": ["Changwon", "Gimhae", "Jinju"],
  "Jeju-do": ["Jeju"],
};
